= Solution Pattern: Migrating from Red Hat Fuse to Red build of Apache Camel
:sectnums:
:sectlinks:
:doctype: book

= Architecture 

The solution pattern leverages preconfigured, ready-to-use Quarkus and Springboot templates.
Those templates contains placeholders where code and configration just need to be copy-pasted from the legacy application.


== Common Challenges 
A major migration is always a technical challenge.

* Custom libraries can show conflicts with new ones; others might be deprecated with a need for a complete rewriting.
* Some important architectural concerns also need to be taken into consideration, like the switch from Fuse Fabric to Red Hat OpenShift as the applications management solution, or moving away from Hawtio as the observability platform.

However, the migration of a Camel application should stick to a Camel-centric discussion, effort and design.

Other elements such as underlying JDK version, underlying runtime characteristics, configuration keys name and values, should not represent a significant part of the migration effort.

As a migration does not bring immediate new business value, it's important that the effort it requires be as low as possible, and that its duration be as short as possible.


[#tech_stack]
== Technology Stack

// Change links and text here as you see fit.
* https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift]
* Red Hat Application Foundation
** https://access.redhat.com/products/quarkus[Quarkus]
** https://developers.redhat.com/products/redhat-build-of-camel/overview[Red Hat build of Camel]


[#in_depth]
== An in-depth look at the solution's architecture

The Red Hat Build of Camel is an Cloud-native, multi-language and a multi-runtime integration stack.
Camel-based integration logic can be written in XML or Java, and can behave as a springboot, a quarkus, or a serverless artifact. 

The present demo will take a legacy API developed in Jboss Fuse 6.2 on Karaf, in Blueprint XML.
It's suggested that such an application targets the Quarkus runtime.
The provided Quarkus template is 100% compatible with CamelK, so the resutling migrated application is immediately ready to be added to a serverless stack.

//// 
[#more_tech]
== About the Technology Stack

If you want to include more details about the tech stack you used, this is the place.
 ////